apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  labels:
    service: example
    app: myapp
    env: prod
    team: fyr
  name: myapp
  namespace: fyr-prod-example
spec:
  maxReplicas: 5
  metrics:
    - resource:
        name: cpu
        target:
          averageUtilization: 70
          type: Utilization
      type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: myapp
