apiVersion: batch/v1
kind: Job
metadata:
  labels:
    service: example
    app: myapp-job
    env: dev
    team: fyr
  name: myapp-job
  namespace: fyr-dev-example
spec:
  template:
    metadata:
      labels:
        service: example
        app: myapp-job
        env: dev
        team: fyr
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  service: example
                  app: myapp-job
                  env: dev
                  team: fyr
              topologyKey: kubernetes.io/hostname
      containers:
        - command:
            - /app/enstrypiont.sh
          image: ghcr.io/kystverket/example/myapp-job:latest
          name: myapp-job
          ports:
            - containerPort: 8080
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsGroup: 10002
            runAsNonRoot: true
            runAsUser: 10002
            seccompProfile:
              type: RuntimeDefault
      imagePullSecrets:
        - name: corp-pull
      restartPolicy: Never
      securityContext:
        fsGroup: 10002
        runAsGroup: 10002
        runAsNonRoot: true
        runAsUser: 10002
