apiVersion: v1
kind: Service
metadata:
  labels:
    service: example
    app: escape
    env: dev
    team: fyr
  name: escape
  namespace: fyr-dev-example
spec:
  ports:
    - name: http-escape
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    service: example
    app: escape
    env: dev
    team: fyr
  type: ClusterIP
