apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  annotations:
    kargo.akuity.io/color: avocado
  labels:
    stage: dev
  name: example-escape-dev
  namespace: fyr-kargo
spec:
  promotionTemplate:
    spec:
      steps:
        - task:
            kind: ClusterPromotionTask
            name: push-image
  requestedFreight:
    - origin:
        kind: Warehouse
        name: example-escape
      sources:
        direct: true
        stages: []
  vars:
    - name: path
      value: _kargo/fyr/dev/example/escape
    - name: image
      value: ghcr.io/kystverket/example/escape
    - name: version
      value: ${{imageFrom(vars.image).Tag}}
