apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: full-entraid
  namespace: aks-istio-ingress
  labels:
    service: repo
    app: full
    env: dev
    team: fyr
spec:
  action: CUSTOM
  provider:
    name: oauth2-proxy
  rules:
    - to:
        - operation:
            hosts:
              - fullexample.dev.corp.cloud/*
              - fullexample.dev.corp.cloud
