apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fyr-admin
  namespace: fyr-kargo
  annotations:
    argocd.argoproj.io/sync-wave: "2"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kargo-admin
subjects:
  - kind: ServiceAccount
    name: fyr-admin
    namespace: fyr-kargo
