apiVersion: v1
kind: Service
metadata:
  labels:
    service: repo
    app: job-example
    env: dev
    team: fyr
  name: job-example
  namespace: fyr-dev-repo
spec:
  ports:
    - name: http-job-example
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    service: repo
    app: job-example
    env: dev
    team: fyr
  type: ClusterIP
